sudo: 'required'

services:
- 'docker'

env:
  global:
    - DOCKER_TAG=0.1.${TRAVIS_BUILD_NUMBER}
    - DOCKER_PUSH=1
  matrix:
    - TARGET=deps
    - TARGET=builder

script:
  - docker login -u ${DOCKER_USERNAME} -p ${DOCKER_PASSWORD}
  - travis_wait 120 make "docker-${TARGET}"

notifications:
  email: false

#branches:
#  only:
#    - develop
